//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace WireFrame
{

    /// <remarks>杆件坐标类型</remarks>
    public static class BarPosType
    {
        public const string upBar = "上弦杆";
        public const string centerBar = "腹杆";
        public const string downBar = "下弦杆";
        public const string boundBar = "上弦杆";
    }
}