//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
namespace WireFrame
{

    /// <remarks>杆件</remarks>
    public interface IBar
    {
        WFBar Info { get; }
        GameObject Body { get; }

        void ShowLine(Material mat, float width);
        void ShowModel(GameObject pfb);
        void SetSize(float r_upBar);
    }

}