//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace WireFrame
{

    /// <remarks>连接节点</remarks>
    public interface INode
    {
        WFNode Info { get; }
        GameObject Body { get; }
        void ShowModel(GameObject node);
        void Hide();
        void SetSize(float r_node);
    }
}
