//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace WireFrame
{

    /// <remarks>空间生成器</remarks>
    public interface IWireCreater
    {
        bool CanCreate(Clamp clamp);
        WireFrameBehaiver Unit(NodeBehaiver node, BarBehaiver bar, Clamp clamp);
        WireFrameBehaiver Create(NodeBehaiver node, BarBehaiver bar, FulcrumBehaiver fulcrum, Clamp clamp);
    }

}