//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine.Events;
using System.Collections;
using System.Linq;
using System.Text;
namespace WireFrame
{

    /// <remarks>空间网架</remarks>
    public interface IWire
    {
        UnityEngine.GameObject Body { get; }

        event UnityAction<IBar> onBarHover;
        event UnityAction<IBar> onBarClicked;
        event UnityAction<INode> onNodeHover;
        event UnityAction<INode> onNodeClicked;
        event UnityAction<IFulcrum> onFulcrumHover;
        event UnityAction<IFulcrum> onFulcrumClicked;

        IEnumerator SwitchToModel(ModelRule modelRule);
        IEnumerator SwitchToLine(LineRule lineRule);
        void ReSetSize(SizeRule sizeRule);
    }
}
